
/**
 * Tencent is pleased to support the open source community by making MSEC available.
 *
 * Copyright (C) 2016 THL A29 Limited, a Tencent company. All rights reserved.
 *
 * Licensed under the GNU General Public License, Version 2.0 (the "License"); 
 * you may not use this file except in compliance with the License. You may 
 * obtain a copy of the License at
 *
 *     https://opensource.org/licenses/GPL-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the 
 * License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing permissions
 * and limitations under the License.
 */


/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class api_lb_msec_org_AccessLB */

#ifndef _Included_api_lb_msec_org_AccessLB
#define _Included_api_lb_msec_org_AccessLB
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     api_lb_msec_org_AccessLB
 * Method:    getroutebyname
 * Signature: (Ljava/lang/String;[B[B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_api_lb_msec_org_AccessLB_getroutebyname
        (JNIEnv *, jobject, jstring, jbyteArray, jbyteArray, jbyteArray);

JNIEXPORT jboolean JNICALL Java_api_lb_msec_org_AccessLB_updateroute
        (JNIEnv *, jobject, jstring, jstring, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
