
/**
 * Tencent is pleased to support the open source community by making MSEC available.
 *
 * Copyright (C) 2016 THL A29 Limited, a Tencent company. All rights reserved.
 *
 * Licensed under the GNU General Public License, Version 2.0 (the "License"); 
 * you may not use this file except in compliance with the License. You may 
 * obtain a copy of the License at
 *
 *     https://opensource.org/licenses/GPL-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the 
 * License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing permissions
 * and limitations under the License.
 */


/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class api_log_msec_org_AccessLog */

#ifndef _Included_api_log_msec_org_AccessLog
#define _Included_api_log_msec_org_AccessLog
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     api_log_msec_org_AccessLog
 * Method:    init
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_api_log_msec_org_AccessLog_init
        (JNIEnv *, jobject, jstring);

/*
 * Class:     api_log_msec_org_AccessLog
 * Method:    setHeader
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_api_log_msec_org_AccessLog_setHeader
                   (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     api_log_msec_org_AccessLog
 * Method:    log
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_api_log_msec_org_AccessLog_log
(JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
